In [1]:
import pandas as pd

In [4]:
import os

In [13]:
os.chdir('/Users/or.bason/Desktop/Python_course') #define the path without the file and after only the file #2

In [20]:
losttb = pd.read_csv('lost-found-adoptable-pets.csv') #read the file (without the path - it was defined before by chdir

In [22]:
losttb.columns

Index(['impound_no', 'Animal_ID', 'Data_Source', 'Record_Type', 'Link',
       'Current_Location', 'Animal_Name', 'animal_type', 'Age',
       'Animal_Gender', 'Animal_Breed', 'Animal_Color', 'Date', 'Date_Type',
       'Obfuscated_Address', 'City', 'State', 'Zip', 'jurisdiction',
       'obfuscated_latitude', 'obfuscated_longitude', 'Image',
       'image_alt_text', 'location_for_map', 'Memo'],
      dtype='object')

In [25]:
losttb.shape

(409, 25)

In [27]:
losttb.tail(3)

,impound_no,Animal_ID,Data_Source,Record_Type,Link,Current_Location,Animal_Name,animal_type,Age,Animal_Gender,...,City,State,Zip,jurisdiction,obfuscated_latitude,obfuscated_longitude,Image,image_alt_text,location_for_map,Memo
406,K17-104272,A544172,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Sadie,Dog,NaN,Female,...,NaN,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,16745 AIR CARGO ROAD\n,NaN
407,K17-103886,A542550,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Maddie,Dog,NaN,Female,...,SEATAC,WA,98188.0,SEATAC,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,"16800 35TH AVE S\nSEATAC, WA 98188\n",NaN
408,K17-103445,A540621,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Chloe,Cat,NaN,Female,...,NaN,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,146TH N.E. AND 26TH AVE.\n,NaN

In [31]:
losttb.loc[20:27] between rows 20-37

,impound_no,Animal_ID,Data_Source,Record_Type,Link,Current_Location,Animal_Name,animal_type,Age,Animal_Gender,...,City,State,Zip,jurisdiction,obfuscated_latitude,obfuscated_longitude,Image,image_alt_text,location_for_map,Memo
20,K17-103887,A542553,Regional Animal Services of King County,FOUND,http://petharbor.com/PublicDetail.asp?searchty...,In Public Home,NaN,Dog,NaN,Female,...,NaN,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,NaN,NaN
21,K17-104154,A543669,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Ava,Dog,NaN,Female,...,KIRKLAND,WA,98034.0,KIRKLAND,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,"12100 NE 150TH ST\nKIRKLAND, WA 98034\n",NaN
22,K17-103714,A541805,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Merlin,Cat,NaN,Male,...,NaN,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,N 6TH AND CUSHMAN ST.\n,NaN
23,K17-103677,A541534,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Lola,Dog,NaN,Female,...,KENT,WA,98032.0,KENT,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,"3300 S 249TH PL\nKENT, WA 98032\n",NaN
24,K17-104479,A545107,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Zoe,Dog,NaN,Female,...,AUBURN,WA,98092.0,KING COUNTY,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,"31900 176TH AVE SE\nAUBURN, WA 98092\n",NaN
25,K17-104055,A543249,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Tidbit,Dog,NaN,Male,...,EDMONDS,WA,98020.0,SNOHOMISH COUNT,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,"200 3RD AVE S\nEDMONDS, WA 98020\n",NaN
26,K17-104450,A544874,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Junebug,Cat,NaN,Female,...,KENT,WA,98042.0,KING COUNTY,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,"16600 SE 240TH ST\nKENT, WA 98042\n",NaN
27,K17-103877,A542542,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Ranica,Cat,NaN,Female,...,NaN,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,HIGHWAY 2\n,NaN

In [62]:
losttb['animal_type'].value_counts()

Cat           287
Dog           102
Dead Cat        8
Goat/sheep      2
Rabbit Sh       2
Dead Dog        2
Hamster         2
Bird            1
Angora          1
Dead Bird       1
Lop-Mini        1
Name: animal_type, dtype: int64

In [66]:
losttb.loc[0:2,'Animal_Name':'Animal_Color']

,Animal_Name,animal_type,Age,Animal_Gender,Animal_Breed,Animal_Color
0,NaN,Cat,NaN,NaN,Domestic Longhair,White / Unknown
1,Neko,Cat,NaN,Male,Domestic Shorthair,Unknown
2,Trixie,Dog,NaN,Female,Jack Russell Terrier,Unknown

In [65]:
losttb.loc[0:2,['Animal_Name','Animal_Color']]

  Animal_Name     Animal_Color
0         NaN  White / Unknown
1        Neko          Unknown
2      Trixie          Unknown

In [73]:
losttb.iloc[:,[0,2,4]]

,impound_no,Data_Source,Link
0,K17-103806,Regional Animal Services of King County,http://petharbor.com/PublicDetail.asp?searchty...
1,K17-103558,Regional Animal Services of King County,http://petharbor.com/PublicDetail.asp?searchty...
2,K17-104020,Regional Animal Services of King County,http://petharbor.com/PublicDetail.asp?searchty...
3,K17-103994,Regional Animal Services of King County,http://petharbor.com/PublicDetail.asp?searchty...
4,K17-104418,Regional Animal Services of King County,http://petharbor.com/PublicDetail.asp?searchty...
...,...,...,...
404,K17-103413,Regional Animal Services of King County,http://petharbor.com/PublicDetail.asp?searchty...
405,K17-104617,Regional Animal Services of King County,http://petharbor.com/PublicDetail.asp?searchty...
406,K17-104272,Regional Animal Services of King County,http://petharbor.com/PublicDetail.asp?searchty...
407,K17-103886,Regional Animal Services of King County,http://petharbor.com/PublicDetail.asp?searchty...
408,K17-103445,Regional Animal Services of King County,http://petharbor.com/PublicDetail.asp?searchty...

In [74]:
losttb['animal_type'].value_counts()

Cat           287
Dog           102
Dead Cat        8
Goat/sheep      2
Rabbit Sh       2
Dead Dog        2
Hamster         2
Bird            1
Angora          1
Dead Bird       1
Lop-Mini        1
Name: animal_type, dtype: int64

In [85]:
losttb.loc[[86, 142, 251, 307],['Record_Type','Animal_Name','Current_Location','City']]

,Record_Type,Animal_Name,Current_Location,City
86,FOUND,Onyx,King County Pet Adoption Center 21615 64TH AVE...,TUKWILA
142,FOUND,Mcgee,Neko,KENT
251,FOUND,Cider,King County Pet Adoption Center 21615 64TH AVE...,KENT
307,FOUND,Cocoa,King County Pet Adoption Center 21615 64TH AVE...,COVINGTON