# IMPORT AND DEFINITION

In [4]:
import pandas as pd #Every time as a start

In [5]:
pwd #where python is looking

'/Users/or.bason'

In [9]:
open('/Users/or.bason/Desktop/Python_course/sample_transactions.csv').read()  #read the file (by payh)  #1

In [5]:
import os

In [9]:
os.chdir('/Users/or.bason/Desktop/Python_course') #define the path without the file and after only the file #2

In [10]:
open('sample_transactions.csv').read()  #read the file (without the path - it was defined before by chdir

'transaction_id,date,product_id,status,payment_method,amount,discount,number_of_items,risk_score,delivery_fee,customer_id,platform\n0029e1f5-b648-4787-b13f-563af8dbe7ff,2019-04-16,b3xjvqj,approved,PayPal,152,0.017005261546893163,6,0.1582092864276342,14,02cf65ec-1ef0-40a6-b44f-36e4c8b644b4,web\n002a2614-807c-47e4-b1c4-a1198a38e058,2018-01-27,3tkc284,declined,Visa,43,0.017763185774012376,1,0.730812803683491,10,02dd9254-23b6-4b32-b53a-17fdfdd8538e,web\n002ae1a3-2aa0-4c54-8cd5-061e2ea126e4,2019-09-28,d7fhbn2,approved,MasterCard,600,0.04194369284943143,3,0.4776380484991445,3,02df87d6-d1cd-494d-a823-97119ec9fece,mobile\n002c1879-5910-46e8-b26b-ae1ae101d035,2018-09-12,YZCTBC4JWQNE627OCIAQRPABAM,approved,Visa,325,0.009637433850003197,7,0.6942332773169644,2,02e09992-334b-468f-8be8-924831e7164c,web\n002c40de-f032-4e10-b5bd-5ee54918cccc,2019-04-14,jj6dcfdg,approved,PayPal,17,0.019171803449324558,6,0.03975967109645584,1,02eb0fde-b132-447e-9493-6a0d66aacc55,web\n002d0a5c-0c06-4ba7-9e7e-750157854e9b,2019-02-06,hteg9fnr,approved,PayPal,462,0.023255632862920057,6,0.7831412825576558,15,02f21e60-18c1-4e86-9c60-8b8cda7dcc5a,web\n002d71fd-f0e9-4c04-8e25-2eab403231b6,2019-02-12,b76yq78,approved,PayPal,314,0.04184283532483648,5,0.17087431366971073,20,02f596d4-94cf-4d16-a039-f9a1cc715b8d,mobile\n002d75df-f207-4218-be5f-e97359c6d7c1,2018-06-17,WJ7DHOEK4WMLFW7OXIJRGYABRY,approved,PayPal,387,0.0031216821479419787,10,0.01415169197888777,15,02f7d55a-957a-43dd-90bf-78f7220a2d86,mobile\n002da95c-f9e2-4612-a53b-ee12b68a97bf,2019-05-27,7BNHPLRSJPBWTGTLMDJWA6HQXA,declined,CreditCard,176,0.036733577916332444,10,0.2854764740589396,16,02fda739-e734-40d6-842c-d3cbe588eb23,mobile\n002ebafd-08da-4002-95cd-08e98aa8e61a,2018-09-24,d72d9gd,approved,Visa,524,0.045328507814592696,7,0.6619729924345861,3,02fdcd8f-e1a9-43d9-b7c2-142c78fc7e90,mobile\n002fc5fc-5e5f-4fe6-8191-44155586ee64,2018-08-31,VECOP7OEMFZEZJS3NX5FLTXLM4,approved,PayPal,540,0.03635500473176784,9,0.38792351243983914,20,02ffb826-75ab-4a8f-b350-478167347a4b,web\n002fe359-4972-4f38-8a5f-559c079f5bac,2019-03-18,mzdqay78,approved,MasterCard,899,0.011437053291056504,3,0.20726843187413668,9,0300a275-5844-40e1-b33d-e324b9bd23cf,web\n0030cddd-ec32-4ed2-949a-9d0c72150f9f,2019-05-14,6VOA6SDH5LR27HCFRGU4P7T3DQ,approved,Visa,292,0.024132288979629102,3,0.2156547461164141,13,0300e554-af2b-4e92-8e22-cdbf1daed028,mobile\n0031bc5c-a945-4023-9b4c-b09dd9cbd138,2018-04-08,7k34qfw,declined,MasterCard,110,0.020343258886596084,1,0.15958554537646108,6,03010d47-62c6-43b9-852b-d753097c8813,web\n003208a2-880b-48ec-927e-f4ca23149543,2018-11-17,NX4FRCEJB6HBCVQ6LYQLPQ5KWQ,declined,Visa,87,0.030718790277614594,2,0.9655849782309445,8,0307b5fd-7238-4ba6-8402-d41aba331ddf,web\n00331cf5-df7a-4fcb-a798-c224998c3799,2019-12-10,AEFYC5YOLGTB4IEOAPX3YTFX4E,declined,MasterCard,629,0.022794593042167754,3,0.2608588457112443,19,0308487d-da1d-473c-a84b-6c42b4617833,web\n00340d42-b059-4375-b7ed-f5f7aeb117f1,2019-08-10,W2JHII6424FHXZYIIESZ2GGXBY,approved,PayPal,241,0.036501513380754254,2,0.7485053059940878,2,03097223-911d-4ce4-a0ea-99b386059eea,web\n00356bd2-8c35-41e9-b442-8403e2dc1e22,2018-07-29,8qz31w6b,approved,PayPal,196,0.020872289951533035,1,0.6814856939862182,9,030a7679-8bbd-4a9c-a3a1-87a5bd8c1026,web\n007369ec-e2be-46e8-90d2-3ce0df47eed0,2018-03-19,jm9dzm6,approved,PayPal,730,0.0219741622724267,7,0.49167828897203136,18,030a901c-ad61-4967-b171-e9fbb70bda65,web\n00850db6-2e9f-4268-87aa-34aa1c652b27,2018-07-23,n474brp,approved,MasterCard,341,0.03308366327679728,7,0.8760910583347066,8,030fa8f0-ee89-49f6-82e4-82d111ef4ab9,web\n0115d59c-c025-4ff4-a0ee-fd2704becff4,2018-04-23,9gz7qasn,approved,PayPal,119,0.015983217175302312,1,0.34207656482688065,6,030fea3e-5eff-4714-af98-28e42bf8e86d,web\n012db262-e4b9-495c-b1c7-eca37b583e57,2019-07-12,AARBJEOLFMKYL4SA2WJ2DS2VS4,approved,Visa,815,0.035385192654127526,7,0.9769107180019909,9,0312ac73-7171-4c25-b35d-5e36ffb4e2e3,web\n0225b9ce-027a-4234-a0e5-7792b9c9239a,2019-03-21,8z6ph32,declined,PayPal,228,0.021465113704127646,9,0.018605923218542708,17,0316fa94-34d1-427e-bd12-21efc963c9bf,web\n02562fb1-8c0c-47c6-a1b2-ad4d301edbfa,2018-01-11,U5DC7KQPEZTFCYNITQMGRFKFQU,approved,PayPal,556,0.014327443325456967,7,0.13840366759434575,6,0318a77f-2ba8-474d-9437-08e6bc70ea3b,mobile\n02c7cf12-9985-4b87-8022-3f210f309050,2018-02-05,MMFZIWL7DZBUCYCYVKRLL6JIA4,approved,PayPal,337,0.000596307976435878,9,0.2231222767041322,10,03199c18-e4ca-4da2-9f3b-3885e07ff715,web\n02cf65ec-1ef0-40a6-b44f-36e4c8b644b4,2019-05-12,dsbjrdd,approved,PayPal,901,0.0012077241254103144,7,0.6843766399898852,10,031e2e7f-2903-40f1-8fe4-d7b6f8663c23,mobile\n02dd9254-23b6-4b32-b53a-17fdfdd8538e,2018-11-17,7r95cmd,approved,PayPal,440,0.042226230671090506,10,0.16709188422999033,4,0321c9ee-5dbe-4839-90f0-bc89db4fa50c,mobile\n02df87d6-d1cd-494d-a823-97119ec9fece,2018-03-25,bgaqgc8f,approved,MasterCard,438,0.00879245936571188,8,0.9639232189725127,0,03237ea3-dad8-44be-88eb-2410f4b4a88d,mobile\n02e09992-334b-468f-8be8-924831e7164c,2019-12-24,67d9xsj,approved,PayPal,382,0.04401692228425992,1,0.2844054924453243,14,03248b92-5fa4-44a7-a1c7-4a615ce67f1a,web\n02eb0fde-b132-447e-9493-6a0d66aacc55,2018-04-20,hh8spmr,approved,Visa,58,0.04950410384963351,7,0.23359586408443023,17,032a3f09-f574-4394-94c6-15f946f56d91,web\n02f21e60-18c1-4e86-9c60-8b8cda7dcc5a,2019-06-21,5g9bkrp,approved,Visa,935,0.02352089978276295,8,0.9700007456336404,0,032aa453-ed36-4327-a898-a3fec4321594,web\n02f596d4-94cf-4d16-a039-f9a1cc715b8d,2019-05-24,A524A3YCILCLJ3HA2TYJTY7AGI,approved,MasterCard,183,0.016492594907114043,4,0.24387568834376128,16,03bb8e3d-5aed-4e1c-97be-50d02aa27dde,web\n02f7d55a-957a-43dd-90bf-78f7220a2d86,2018-10-30,Z4CPPBMASTC47QB52GQ7E7Y3LA,declined,Visa,956,0.021434028260537023,5,0.5375412736998658,16,04b75a10-7993-47c4-bfc6-a3d100954355,web\n02fda739-e734-40d6-842c-d3cbe588eb23,2019-07-06,7p9nj8j,declined,Visa,368,0.015789413041708382,5,0.4962244160923911,5,04c314a5-fcb3-4550-8844-6fe118ed2ae9,mobile\n02fdcd8f-e1a9-43d9-b7c2-142c78fc7e90,2019-02-02,,approved,Visa,413,0.003352561130327142,5,0.7227967308816019,15,0502f9e6-4609-4e84-8378-c649203e5622,web\n02ffb826-75ab-4a8f-b350-478167347a4b,2019-12-20,3dzwkdy,approved,PayPal,608,0.0010229508973488954,8,0.7628784068741837,12,0599c49b-2da8-422c-81bf-0617a1d970d2,mobile\n0300a275-5844-40e1-b33d-e324b9bd23cf,2018-12-19,MU42GW6T7W2Y7EAXL3VLPUPVSU,approved,PayPal,562,0.015331769057818296,4,0.4786507468040072,0,05a1bacf-2980-415b-a355-e67bca53fcfa,web\n0300e554-af2b-4e92-8e22-cdbf1daed028,2019-11-25,g4x3rr4,declined,PayPal,694,0.03442548603023002,6,0.65514918067877,10,05a83064-6798-4409-b0df-de90d659b89d,mobile\n03010d47-62c6-43b9-852b-d753097c8813,2019-08-16,6GP3WLFJK2IRJFGYLRA2FXEBTY,approved,MasterCard,563,0.04345102655525473,3,0.019966430643881816,17,05abb296-c7fd-4c2f-8d47-8a173106d90f,web\n0307b5fd-7238-4ba6-8402-d41aba331ddf,2019-01-18,ckray5xd,approved,MasterCard,604,0.044472182688647825,7,0.9683967570534177,0,05b8916d-b217-4caf-afe1-48e64015c1e5,web\n02f7d55a-957a-43dd-90bf-78f7220a2d86,2018-08-28,mgb3m44,declined,MasterCard,100,0.04752143651440534,6,0.603460612958242,18,05bb8b02-28a8-471a-ae19-2c8eb55dac53,mobile\n'

# Create Table and Read

In [11]:
tran=pd.read_csv('sample_transactions.csv')    #create and read the table

In [30]:
 tran.columns   #get the fields names into the table   -- #objects is a text(string)

Index(['transaction_id', 'date', 'product_id', 'status', 'payment_method',
       'amount', 'discount', 'number_of_items', 'risk_score', 'delivery_fee',
       'customer_id', 'platform'],
      dtype='object')

In [31]:
tran.info()  #info of the fields into table  -- Name/type/howmany nulls

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   transaction_id   41 non-null     object
 1   date             41 non-null     object
 2   product_id       40 non-null     object
 3   status           41 non-null     object
 4   payment_method   41 non-null     object
 5   amount           41 non-null     int64
 6   discount         41 non-null     float64
 7   number_of_items  41 non-null     int64
 8   risk_score       41 non-null     float64
 9   delivery_fee     41 non-null     int64
 10  customer_id      41 non-null     object
 11  platform         41 non-null     object
dtypes: float64(2), int64(3), object(7)
memory usage: 4.0+ KB

In [33]:
tran.shape   #what is the shape of the table - 41 on 12

(41, 12)

In [34]:
tran.size   #how many values- total

492

# Get values from Table

In [32]:
tran['product_id']        #get a values from table - tran withput nothing is all the fields in table  #one field

0                        b3xjvqj
1                        3tkc284
2                        d7fhbn2
3     YZCTBC4JWQNE627OCIAQRPABAM
4                       jj6dcfdg
5                       hteg9fnr
6                        b76yq78
7     WJ7DHOEK4WMLFW7OXIJRGYABRY
8     7BNHPLRSJPBWTGTLMDJWA6HQXA
9                        d72d9gd
10    VECOP7OEMFZEZJS3NX5FLTXLM4
11                      mzdqay78
12    6VOA6SDH5LR27HCFRGU4P7T3DQ
13                       7k34qfw
14    NX4FRCEJB6HBCVQ6LYQLPQ5KWQ
15    AEFYC5YOLGTB4IEOAPX3YTFX4E
16    W2JHII6424FHXZYIIESZ2GGXBY
17                      8qz31w6b
18                       jm9dzm6
19                       n474brp
20                      9gz7qasn
21    AARBJEOLFMKYL4SA2WJ2DS2VS4
22                       8z6ph32
23    U5DC7KQPEZTFCYNITQMGRFKFQU
24    MMFZIWL7DZBUCYCYVKRLL6JIA4
25                       dsbjrdd
26                       7r95cmd
27                      bgaqgc8f
28                       67d9xsj
29                       hh8spmr
30                       5g9bkrp
31    A524A3YCILCLJ3HA2TYJTY7AGI
32    Z4CPPBMASTC47QB52GQ7E7Y3LA
33                       7p9nj8j
34                           NaN
35                       3dzwkdy
36    MU42GW6T7W2Y7EAXL3VLPUPVSU
37                       g4x3rr4
38    6GP3WLFJK2IRJFGYLRA2FXEBTY
39                      ckray5xd
40                       mgb3m44
Name: product_id, dtype: object

In [53]:
cols=tran['product_id','transaction_id','status']    #more than 1 fields   #twice[]
tran[cols]

KeyError: ('product_id', 'transaction_id', 'status')

# Function

In [47]:
tran.head(2) #first 2 rows

,transaction_id,date,product_id,status,payment_method,amount,discount,number_of_items,risk_score,delivery_fee,customer_id,platform
0,0029e1f5-b648-4787-b13f-563af8dbe7ff,2019-04-16,b3xjvqj,approved,PayPal,152,0.017005,6,0.158209,14,02cf65ec-1ef0-40a6-b44f-36e4c8b644b4,web
1,002a2614-807c-47e4-b1c4-a1198a38e058,2018-01-27,3tkc284,declined,Visa,43,0.017763,1,0.730813,10,02dd9254-23b6-4b32-b53a-17fdfdd8538e,web

In [49]:
tran.tail(2) #last 2 rows

,transaction_id,date,product_id,status,payment_method,amount,discount,number_of_items,risk_score,delivery_fee,customer_id,platform
39,0307b5fd-7238-4ba6-8402-d41aba331ddf,2019-01-18,ckray5xd,approved,MasterCard,604,0.044472,7,0.968397,0,05b8916d-b217-4caf-afe1-48e64015c1e5,web
40,02f7d55a-957a-43dd-90bf-78f7220a2d86,2018-08-28,mgb3m44,declined,MasterCard,100,0.047521,6,0.603461,18,05bb8b02-28a8-471a-ae19-2c8eb55dac53,mobile

In [50]:
tran.sample(2) #middle (center) 2 rows

,transaction_id,date,product_id,status,payment_method,amount,discount,number_of_items,risk_score,delivery_fee,customer_id,platform
34,02fdcd8f-e1a9-43d9-b7c2-142c78fc7e90,2019-02-02,NaN,approved,Visa,413,0.003353,5,0.722797,15,0502f9e6-4609-4e84-8378-c649203e5622,web
20,0115d59c-c025-4ff4-a0ee-fd2704becff4,2018-04-23,9gz7qasn,approved,PayPal,119,0.015983,1,0.342077,6,030fea3e-5eff-4714-af98-28e42bf8e86d,web

In [52]:
tran.describe()  #creating statistic report of the table as a summary (only for the numbers)

           amount   discount  number_of_items  risk_score  delivery_fee
count   41.000000  41.000000        41.000000   41.000000     41.000000
mean   422.560976   0.024740         5.512195    0.475667     10.073171
std    263.134571   0.014324         2.739726    0.306536      6.345826
min     17.000000   0.000596         1.000000    0.014152      0.000000
25%    196.000000   0.015789         3.000000    0.215655      5.000000
50%    387.000000   0.021974         6.000000    0.478651     10.000000
75%    600.000000   0.036502         7.000000    0.722797     16.000000
max    956.000000   0.049504        10.000000    0.976911     20.000000

# Create Dataframe

In [54]:
tran[['product_id']]  #[[X2]]

                    product_id
0                      b3xjvqj
1                      3tkc284
2                      d7fhbn2
3   YZCTBC4JWQNE627OCIAQRPABAM
4                     jj6dcfdg
5                     hteg9fnr
6                      b76yq78
7   WJ7DHOEK4WMLFW7OXIJRGYABRY
8   7BNHPLRSJPBWTGTLMDJWA6HQXA
9                      d72d9gd
10  VECOP7OEMFZEZJS3NX5FLTXLM4
11                    mzdqay78
12  6VOA6SDH5LR27HCFRGU4P7T3DQ
13                     7k34qfw
14  NX4FRCEJB6HBCVQ6LYQLPQ5KWQ
15  AEFYC5YOLGTB4IEOAPX3YTFX4E
16  W2JHII6424FHXZYIIESZ2GGXBY
17                    8qz31w6b
18                     jm9dzm6
19                     n474brp
20                    9gz7qasn
21  AARBJEOLFMKYL4SA2WJ2DS2VS4
22                     8z6ph32
23  U5DC7KQPEZTFCYNITQMGRFKFQU
24  MMFZIWL7DZBUCYCYVKRLL6JIA4
25                     dsbjrdd
26                     7r95cmd
27                    bgaqgc8f
28                     67d9xsj
29                     hh8spmr
30                     5g9bkrp
31  A524A3YCILCLJ3HA2TYJTY7AGI
32  Z4CPPBMASTC47QB52GQ7E7Y3LA
33                     7p9nj8j
34                         NaN
35                     3dzwkdy
36  MU42GW6T7W2Y7EAXL3VLPUPVSU
37                     g4x3rr4
38  6GP3WLFJK2IRJFGYLRA2FXEBTY
39                    ckray5xd
40                     mgb3m44

# Function

In [57]:
tran['number_of_items'].std()

2.739725818576671

In [58]:
tran #get all the table

,transaction_id,date,product_id,status,payment_method,amount,discount,number_of_items,risk_score,delivery_fee,customer_id,platform
0,0029e1f5-b648-4787-b13f-563af8dbe7ff,2019-04-16,b3xjvqj,approved,PayPal,152,0.017005,6,0.158209,14,02cf65ec-1ef0-40a6-b44f-36e4c8b644b4,web
1,002a2614-807c-47e4-b1c4-a1198a38e058,2018-01-27,3tkc284,declined,Visa,43,0.017763,1,0.730813,10,02dd9254-23b6-4b32-b53a-17fdfdd8538e,web
2,002ae1a3-2aa0-4c54-8cd5-061e2ea126e4,2019-09-28,d7fhbn2,approved,MasterCard,600,0.041944,3,0.477638,3,02df87d6-d1cd-494d-a823-97119ec9fece,mobile
3,002c1879-5910-46e8-b26b-ae1ae101d035,2018-09-12,YZCTBC4JWQNE627OCIAQRPABAM,approved,Visa,325,0.009637,7,0.694233,2,02e09992-334b-468f-8be8-924831e7164c,web
4,002c40de-f032-4e10-b5bd-5ee54918cccc,2019-04-14,jj6dcfdg,approved,PayPal,17,0.019172,6,0.039760,1,02eb0fde-b132-447e-9493-6a0d66aacc55,web
5,002d0a5c-0c06-4ba7-9e7e-750157854e9b,2019-02-06,hteg9fnr,approved,PayPal,462,0.023256,6,0.783141,15,02f21e60-18c1-4e86-9c60-8b8cda7dcc5a,web
6,002d71fd-f0e9-4c04-8e25-2eab403231b6,2019-02-12,b76yq78,approved,PayPal,314,0.041843,5,0.170874,20,02f596d4-94cf-4d16-a039-f9a1cc715b8d,mobile
7,002d75df-f207-4218-be5f-e97359c6d7c1,2018-06-17,WJ7DHOEK4WMLFW7OXIJRGYABRY,approved,PayPal,387,0.003122,10,0.014152,15,02f7d55a-957a-43dd-90bf-78f7220a2d86,mobile
8,002da95c-f9e2-4612-a53b-ee12b68a97bf,2019-05-27,7BNHPLRSJPBWTGTLMDJWA6HQXA,declined,CreditCard,176,0.036734,10,0.285476,16,02fda739-e734-40d6-842c-d3cbe588eb23,mobile
9,002ebafd-08da-4002-95cd-08e98aa8e61a,2018-09-24,d72d9gd,approved,Visa,524,0.045329,7,0.661973,3,02fdcd8f-e1a9-43d9-b7c2-142c78fc7e90,mobile
10,002fc5fc-5e5f-4fe6-8191-44155586ee64,2018-08-31,VECOP7OEMFZEZJS3NX5FLTXLM4,approved,PayPal,540,0.036355,9,0.387924,20,02ffb826-75ab-4a8f-b350-478167347a4b,web
11,002fe359-4972-4f38-8a5f-559c079f5bac,2019-03-18,mzdqay78,approved,MasterCard,899,0.011437,3,0.207268,9,0300a275-5844-40e1-b33d-e324b9bd23cf,web
12,0030cddd-ec32-4ed2-949a-9d0c72150f9f,2019-05-14,6VOA6SDH5LR27HCFRGU4P7T3DQ,approved,Visa,292,0.024132,3,0.215655,13,0300e554-af2b-4e92-8e22-cdbf1daed028,mobile
13,0031bc5c-a945-4023-9b4c-b09dd9cbd138,2018-04-08,7k34qfw,declined,MasterCard,110,0.020343,1,0.159586,6,03010d47-62c6-43b9-852b-d753097c8813,web
14,003208a2-880b-48ec-927e-f4ca23149543,2018-11-17,NX4FRCEJB6HBCVQ6LYQLPQ5KWQ,declined,Visa,87,0.030719,2,0.965585,8,0307b5fd-7238-4ba6-8402-d41aba331ddf,web
15,00331cf5-df7a-4fcb-a798-c224998c3799,2019-12-10,AEFYC5YOLGTB4IEOAPX3YTFX4E,declined,MasterCard,629,0.022795,3,0.260859,19,0308487d-da1d-473c-a84b-6c42b4617833,web
16,00340d42-b059-4375-b7ed-f5f7aeb117f1,2019-08-10,W2JHII6424FHXZYIIESZ2GGXBY,approved,PayPal,241,0.036502,2,0.748505,2,03097223-911d-4ce4-a0ea-99b386059eea,web
17,00356bd2-8c35-41e9-b442-8403e2dc1e22,2018-07-29,8qz31w6b,approved,PayPal,196,0.020872,1,0.681486,9,030a7679-8bbd-4a9c-a3a1-87a5bd8c1026,web
18,007369ec-e2be-46e8-90d2-3ce0df47eed0,2018-03-19,jm9dzm6,approved,PayPal,730,0.021974,7,0.491678,18,030a901c-ad61-4967-b171-e9fbb70bda65,web
19,00850db6-2e9f-4268-87aa-34aa1c652b27,2018-07-23,n474brp,approved,MasterCard,341,0.033084,7,0.876091,8,030fa8f0-ee89-49f6-82e4-82d111ef4ab9,web
20,0115d59c-c025-4ff4-a0ee-fd2704becff4,2018-04-23,9gz7qasn,approved,PayPal,119,0.015983,1,0.342077,6,030fea3e-5eff-4714-af98-28e42bf8e86d,web
21,012db262-e4b9-495c-b1c7-eca37b583e57,2019-07-12,AARBJEOLFMKYL4SA2WJ2DS2VS4,approved,Visa,815,0.035385,7,0.976911,9,0312ac73-7171-4c25-b35d-5e36ffb4e2e3,web
22,0225b9ce-027a-4234-a0e5-7792b9c9239a,2019-03-21,8z6ph32,declined,PayPal,228,0.021465,9,0.018606,17,0316fa94-34d1-427e-bd12-21efc963c9bf,web
23,02562fb1-8c0c-47c6-a1b2-ad4d301edbfa,2018-01-11,U5DC7KQPEZTFCYNITQMGRFKFQU,approved,PayPal,556,0.014327,7,0.138404,6,0318a77f-2ba8-474d-9437-08e6bc70ea3b,mobile
24,02c7cf12-9985-4b87-8022-3f210f309050,2018-02-05,MMFZIWL7DZBUCYCYVKRLL6JIA4,approved,PayPal,337,0.000596,9,0.223122,10,03199c18-e4ca-4da2-9f3b-3885e07ff715,web
25,02cf65ec-1ef0-40a6-b44f-36e4c8b644b4,2019-05-12,dsbjrdd,approved,PayPal,901,0.001208,7,0.684377,10,031e2e7f-2903-40f1-8fe4-d7b6f8663c23,mobile
26,02dd9254-23b6-4b32-b53a-17fdfdd8538e,2018-11-17,7r95cmd,approved,PayPal,440,0.042226,10,0.167092,4,0321c9ee-5dbe-4839-90f0-bc89db4fa50c,mobile
27,02df87d6-d1cd-494d-a823-97119ec9fece,2018-03-25,bgaqgc8f,approved,MasterCard,438,0.008792,8,0.963923,0,03237ea3-dad8-44be-88eb-2410f4b4a88d,mobile
28,02e09992-334b-468f-8be8-924831e7164c,2019-12-24,67d9xsj,approved,PayPal,382,0.044017,1,0.284405,14,03248b92-5fa4-44a7-a1c7-4a615ce67f1a,web
29,02eb0fde-b132-447e-9493-6a0d66aacc55,2018-04-20,hh8spmr,approved,Visa,58,0.049504,7,0.233596,17,032a3f09-f574-4394-94c6-15f946f56d91,web
30,02f21e60-18c1-4e86-9c60-8b8cda7dcc5a,2019-06-21,5g9bkrp,approved,Visa,935,0.023521,8,0.970001,0,032aa453-ed36-4327-a898-a3fec4321594,web
31,02f596d4-94cf-4d16-a039-f9a1cc715b8d,2019-05-24,A524A3YCILCLJ3HA2TYJTY7AGI,approved,MasterCard,183,0.016493,4,0.243876,16,03bb8e3d-5aed-4e1c-97be-50d02aa27dde,web
32,02f7d55a-957a-43dd-90bf-78f7220a2d86,2018-10-30,Z4CPPBMASTC47QB52GQ7E7Y3LA,declined,Visa,956,0.021434,5,0.537541,16,04b75a10-7993-47c4-bfc6-a3d100954355,web
33,02fda739-e734-40d6-842c-d3cbe588eb23,2019-07-06,7p9nj8j,declined,Visa,368,0.015789,5,0.496224,5,04c314a5-fcb3-4550-8844-6fe118ed2ae9,mobile
34,02fdcd8f-e1a9-43d9-b7c2-142c78fc7e90,2019-02-02,NaN,approved,Visa,413,0.003353,5,0.722797,15,0502f9e6-4609-4e84-8378-c649203e5622,web
35,02ffb826-75ab-4a8f-b350-478167347a4b,2019-12-20,3dzwkdy,approved,PayPal,608,0.001023,8,0.762878,12,0599c49b-2da8-422c-81bf-0617a1d970d2,mobile
36,0300a275-5844-40e1-b33d-e324b9bd23cf,2018-12-19,MU42GW6T7W2Y7EAXL3VLPUPVSU,approved,PayPal,562,0.015332,4,0.478651,0,05a1bacf-2980-415b-a355-e67bca53fcfa,web
37,0300e554-af2b-4e92-8e22-cdbf1daed028,2019-11-25,g4x3rr4,declined,PayPal,694,0.034425,6,0.655149,10,05a83064-6798-4409-b0df-de90d659b89d,mobile
38,03010d47-62c6-43b9-852b-d753097c8813,2019-08-16,6GP3WLFJK2IRJFGYLRA2FXEBTY,approved,MasterCard,563,0.043451,3,0.019966,17,05abb296-c7fd-4c2f-8d47-8a173106d90f,web
39,0307b5fd-7238-4ba6-8402-d41aba331ddf,2019-01-18,ckray5xd,approved,MasterCard,604,0.044472,7,0.968397,0,05b8916d-b217-4caf-afe1-48e64015c1e5,web
40,02f7d55a-957a-43dd-90bf-78f7220a2d86,2018-08-28,mgb3m44,declined,MasterCard,100,0.047521,6,0.603461,18,05bb8b02-28a8-471a-ae19-2c8eb55dac53,mobile

In [59]:
tran['payment_method'].value_counts()  #like group by for counting by the choosen field

PayPal        19
Visa          11
MasterCard    10
CreditCard     1
Name: payment_method, dtype: int64

In [62]:
tran['payment_method'].value_counts(normalize = True)  #in %

PayPal        0.463415
Visa          0.268293
MasterCard    0.243902
CreditCard    0.024390
Name: payment_method, dtype: float64

In [71]:
counts=tran['payment_method'].value_counts(normalize = True).to_frame()  #Insert to_frame the normalize resault to counts
counts.insert(0,'counts',tran['payment_method'].value_counts())          #Insert the simple count to the counts table (frame)
counts                                                                   #Get the table

# Normalized & agg_Sourcevalues

            counts  payment_method
PayPal          19        0.463415
Visa            11        0.268293
MasterCard      10        0.243902
CreditCard       1        0.024390

In [70]:
tran.T  #Trasnpose the table

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
transaction_id,0029e1f5-b648-4787-b13f-563af8dbe7ff,002a2614-807c-47e4-b1c4-a1198a38e058,002ae1a3-2aa0-4c54-8cd5-061e2ea126e4,002c1879-5910-46e8-b26b-ae1ae101d035,002c40de-f032-4e10-b5bd-5ee54918cccc,002d0a5c-0c06-4ba7-9e7e-750157854e9b,002d71fd-f0e9-4c04-8e25-2eab403231b6,002d75df-f207-4218-be5f-e97359c6d7c1,002da95c-f9e2-4612-a53b-ee12b68a97bf,002ebafd-08da-4002-95cd-08e98aa8e61a,...,02f596d4-94cf-4d16-a039-f9a1cc715b8d,02f7d55a-957a-43dd-90bf-78f7220a2d86,02fda739-e734-40d6-842c-d3cbe588eb23,02fdcd8f-e1a9-43d9-b7c2-142c78fc7e90,02ffb826-75ab-4a8f-b350-478167347a4b,0300a275-5844-40e1-b33d-e324b9bd23cf,0300e554-af2b-4e92-8e22-cdbf1daed028,03010d47-62c6-43b9-852b-d753097c8813,0307b5fd-7238-4ba6-8402-d41aba331ddf,02f7d55a-957a-43dd-90bf-78f7220a2d86
date,2019-04-16,2018-01-27,2019-09-28,2018-09-12,2019-04-14,2019-02-06,2019-02-12,2018-06-17,2019-05-27,2018-09-24,...,2019-05-24,2018-10-30,2019-07-06,2019-02-02,2019-12-20,2018-12-19,2019-11-25,2019-08-16,2019-01-18,2018-08-28
product_id,b3xjvqj,3tkc284,d7fhbn2,YZCTBC4JWQNE627OCIAQRPABAM,jj6dcfdg,hteg9fnr,b76yq78,WJ7DHOEK4WMLFW7OXIJRGYABRY,7BNHPLRSJPBWTGTLMDJWA6HQXA,d72d9gd,...,A524A3YCILCLJ3HA2TYJTY7AGI,Z4CPPBMASTC47QB52GQ7E7Y3LA,7p9nj8j,NaN,3dzwkdy,MU42GW6T7W2Y7EAXL3VLPUPVSU,g4x3rr4,6GP3WLFJK2IRJFGYLRA2FXEBTY,ckray5xd,mgb3m44
status,approved,declined,approved,approved,approved,approved,approved,approved,declined,approved,...,approved,declined,declined,approved,approved,approved,declined,approved,approved,declined
payment_method,PayPal,Visa,MasterCard,Visa,PayPal,PayPal,PayPal,PayPal,CreditCard,Visa,...,MasterCard,Visa,Visa,Visa,PayPal,PayPal,PayPal,MasterCard,MasterCard,MasterCard
amount,152,43,600,325,17,462,314,387,176,524,...,183,956,368,413,608,562,694,563,604,100
discount,0.017005,0.017763,0.041944,0.009637,0.019172,0.023256,0.041843,0.003122,0.036734,0.045329,...,0.016493,0.021434,0.015789,0.003353,0.001023,0.015332,0.034425,0.043451,0.044472,0.047521
number_of_items,6,1,3,7,6,6,5,10,10,7,...,4,5,5,5,8,4,6,3,7,6
risk_score,0.158209,0.730813,0.477638,0.694233,0.03976,0.783141,0.170874,0.014152,0.285476,0.661973,...,0.243876,0.537541,0.496224,0.722797,0.762878,0.478651,0.655149,0.019966,0.968397,0.603461
delivery_fee,14,10,3,2,1,15,20,15,16,3,...,16,16,5,15,12,0,10,17,0,18
customer_id,02cf65ec-1ef0-40a6-b44f-36e4c8b644b4,02dd9254-23b6-4b32-b53a-17fdfdd8538e,02df87d6-d1cd-494d-a823-97119ec9fece,02e09992-334b-468f-8be8-924831e7164c,02eb0fde-b132-447e-9493-6a0d66aacc55,02f21e60-18c1-4e86-9c60-8b8cda7dcc5a,02f596d4-94cf-4d16-a039-f9a1cc715b8d,02f7d55a-957a-43dd-90bf-78f7220a2d86,02fda739-e734-40d6-842c-d3cbe588eb23,02fdcd8f-e1a9-43d9-b7c2-142c78fc7e90,...,03bb8e3d-5aed-4e1c-97be-50d02aa27dde,04b75a10-7993-47c4-bfc6-a3d100954355,04c314a5-fcb3-4550-8844-6fe118ed2ae9,0502f9e6-4609-4e84-8378-c649203e5622,0599c49b-2da8-422c-81bf-0617a1d970d2,05a1bacf-2980-415b-a355-e67bca53fcfa,05a83064-6798-4409-b0df-de90d659b89d,05abb296-c7fd-4c2f-8d47-8a173106d90f,05b8916d-b217-4caf-afe1-48e64015c1e5,05bb8b02-28a8-471a-ae19-2c8eb55dac53
platform,web,web,mobile,web,web,web,mobile,mobile,mobile,mobile,...,web,web,mobile,web,mobile,web,mobile,web,web,mobile

In [99]:
pets=pd.read_csv('lost-found-adoptable-pets.csv',usecols=['impound_no','Animal_ID','Record_Type','Current_Location','Data_Source','Animal_Gender','Animal_Breed','Animal_Color','Animal_Name'],index_col='impound_no')  #read only clolumns that i need)
pets

,Animal_ID,Data_Source,Record_Type,Current_Location,Animal_Name,Animal_Gender,Animal_Breed,Animal_Color
impound_no,,,,,,,,
K17-103806,A542208,Regional Animal Services of King County,FOUND,In Public Home,NaN,NaN,Domestic Longhair,White / Unknown
K17-103558,A541114,Regional Animal Services of King County,LOST,LOST,Neko,Male,Domestic Shorthair,Unknown
K17-104020,A543155,Regional Animal Services of King County,LOST,LOST,Trixie,Female,Jack Russell Terrier,Unknown
K17-103994,A543033,Regional Animal Services of King County,FOUND,In Public Home,NaN,Female,Yorkshire Terrier,Brown / Black
K17-104418,A544774,Regional Animal Services of King County,LOST,LOST,Kitty,Female,Manx,Unknown
...,...,...,...,...,...,...,...,...
K17-103413,A540407,Regional Animal Services of King County,LOST,LOST,Monster,Male,Siamese,Unknown
K17-104617,A545630,Regional Animal Services of King County,LOST,LOST,Tyson,Male,Rottweiler,Unknown
K17-104272,A544172,Regional Animal Services of King County,LOST,LOST,Sadie,Female,German Shepherd,Unknown
K17-103886,A542550,Regional Animal Services of King County,LOST,LOST,Maddie,Female,Boxer,Unknown
K17-103445,A540621,Regional Animal Services of King County,LOST,LOST,Chloe,Female,Domestic Shorthair,Unknown

# loc function

In [98]:
pets.loc['K17-103558']  #loc=location - find a columns and details by value

Animal_ID                                           A541114
Data_Source         Regional Animal Services of King County
Record_Type                                            LOST
Current_Location                                       LOST
Animal_Name                                            Neko
Animal_Gender                                          Male
Animal_Breed                             Domestic Shorthair
Animal_Color                                        Unknown
Name: K17-103558, dtype: object

In [92]:
pets.loc['K17-103558','Animal_Name']  #loc=location - find a specific columns and details by value #here is the name

'Neko'

In [93]:
pets.head(2) #sample of 2 head rows

,Animal_ID,Data_Source,Record_Type,Current_Location,Animal_Name,Animal_Gender,Animal_Breed,Animal_Color
impound_no,,,,,,,,
K17-103806,A542208,Regional Animal Services of King County,FOUND,In Public Home,NaN,NaN,Domestic Longhair,White / Unknown
K17-103558,A541114,Regional Animal Services of King County,LOST,LOST,Neko,Male,Domestic Shorthair,Unknown

In [101]:
pets.loc[['K17-103558','K17-104020','K17-103806'],['Animal_Name','Record_Type','Current_Location','Animal_Name']]
#for 3 specific value (impound_no) give me the coulumns that mentioned

           Animal_Name Record_Type Current_Location Animal_Name
impound_no
K17-103558        Neko        LOST             LOST        Neko
K17-104020      Trixie        LOST             LOST      Trixie
K17-103806         NaN       FOUND   In Public Home         NaN

In [102]:
pets.loc['K17-104020':'K17-104362']  #Range between

,Animal_ID,Data_Source,Record_Type,Current_Location,Animal_Name,Animal_Gender,Animal_Breed,Animal_Color
impound_no,,,,,,,,
K17-104020,A543155,Regional Animal Services of King County,LOST,LOST,Trixie,Female,Jack Russell Terrier,Unknown
K17-103994,A543033,Regional Animal Services of King County,FOUND,In Public Home,NaN,Female,Yorkshire Terrier,Brown / Black
K17-104418,A544774,Regional Animal Services of King County,LOST,LOST,Kitty,Female,Manx,Unknown
K17-096407,A519032,Regional Animal Services of King County,LOST,LOST,NaN,Male,Beagle,Unknown
K17-103309,A539944,Regional Animal Services of King County,LOST,LOST,Captain,Male,Siberian Husky,Unknown
K17-103962,A542906,Regional Animal Services of King County,LOST,LOST,Gizmo,Male,Domestic Shorthair,Unknown
K17-104362,A544414,Regional Animal Services of King County,LOST,LOST,NaN,Male,Domestic Mediumhair,Unknown

In [104]:
pets.loc['K17-104020':'K17-104362',['Animal_Name','Record_Type','Current_Location']] 
#Range between with specific columns

           Animal_Name Record_Type Current_Location
impound_no
K17-104020      Trixie        LOST             LOST
K17-103994         NaN       FOUND   In Public Home
K17-104418       Kitty        LOST             LOST
K17-096407         NaN        LOST             LOST
K17-103309     Captain        LOST             LOST
K17-103962       Gizmo        LOST             LOST
K17-104362         NaN        LOST             LOST

In [106]:
pets.iloc[:5]      #get a rows by num_rows- from first row to the number that inserted and all the columns

,Animal_ID,Data_Source,Record_Type,Current_Location,Animal_Name,Animal_Gender,Animal_Breed,Animal_Color
impound_no,,,,,,,,
K17-103806,A542208,Regional Animal Services of King County,FOUND,In Public Home,NaN,NaN,Domestic Longhair,White / Unknown
K17-103558,A541114,Regional Animal Services of King County,LOST,LOST,Neko,Male,Domestic Shorthair,Unknown
K17-104020,A543155,Regional Animal Services of King County,LOST,LOST,Trixie,Female,Jack Russell Terrier,Unknown
K17-103994,A543033,Regional Animal Services of King County,FOUND,In Public Home,NaN,Female,Yorkshire Terrier,Brown / Black
K17-104418,A544774,Regional Animal Services of King County,LOST,LOST,Kitty,Female,Manx,Unknown

In [109]:
pets.iloc[:-1]   #get a all the rows axcept to the last row and all the columns

,Animal_ID,Data_Source,Record_Type,Current_Location,Animal_Name,Animal_Gender,Animal_Breed,Animal_Color
impound_no,,,,,,,,
K17-103806,A542208,Regional Animal Services of King County,FOUND,In Public Home,NaN,NaN,Domestic Longhair,White / Unknown
K17-103558,A541114,Regional Animal Services of King County,LOST,LOST,Neko,Male,Domestic Shorthair,Unknown
K17-104020,A543155,Regional Animal Services of King County,LOST,LOST,Trixie,Female,Jack Russell Terrier,Unknown
K17-103994,A543033,Regional Animal Services of King County,FOUND,In Public Home,NaN,Female,Yorkshire Terrier,Brown / Black
K17-104418,A544774,Regional Animal Services of King County,LOST,LOST,Kitty,Female,Manx,Unknown
...,...,...,...,...,...,...,...,...
K17-104385,A544492,Regional Animal Services of King County,LOST,LOST,Hudson,Male,Labrador Retriever,Unknown
K17-103413,A540407,Regional Animal Services of King County,LOST,LOST,Monster,Male,Siamese,Unknown
K17-104617,A545630,Regional Animal Services of King County,LOST,LOST,Tyson,Male,Rottweiler,Unknown
K17-104272,A544172,Regional Animal Services of King County,LOST,LOST,Sadie,Female,German Shepherd,Unknown
K17-103886,A542550,Regional Animal Services of King County,LOST,LOST,Maddie,Female,Boxer,Unknown

In [110]:
pets.iloc[:5,:4] # 5 first rows and 4 first columns at the table

,Animal_ID,Data_Source,Record_Type,Current_Location
impound_no,,,,
K17-103806,A542208,Regional Animal Services of King County,FOUND,In Public Home
K17-103558,A541114,Regional Animal Services of King County,LOST,LOST
K17-104020,A543155,Regional Animal Services of King County,LOST,LOST
K17-103994,A543033,Regional Animal Services of King County,FOUND,In Public Home
K17-104418,A544774,Regional Animal Services of King County,LOST,LOST

In [114]:
pets.iloc[:5].loc[:,'Data_Source':'Animal_Gender']  #involve iloc and names that not in number

,Data_Source,Record_Type,Current_Location,Animal_Name,Animal_Gender
impound_no,,,,,
K17-103806,Regional Animal Services of King County,FOUND,In Public Home,NaN,NaN
K17-103558,Regional Animal Services of King County,LOST,LOST,Neko,Male
K17-104020,Regional Animal Services of King County,LOST,LOST,Trixie,Female
K17-103994,Regional Animal Services of King County,FOUND,In Public Home,NaN,Female
K17-104418,Regional Animal Services of King County,LOST,LOST,Kitty,Female

# Filtering

In [128]:
pets=pd.read_csv('lost-found-adoptable-pets.csv') #Reaset and read the data again
pets

,impound_no,Animal_ID,Data_Source,Record_Type,Link,Current_Location,Animal_Name,animal_type,Age,Animal_Gender,...,City,State,Zip,jurisdiction,obfuscated_latitude,obfuscated_longitude,Image,image_alt_text,location_for_map,Memo
0,K17-103806,A542208,Regional Animal Services of King County,FOUND,http://petharbor.com/PublicDetail.asp?searchty...,In Public Home,NaN,Cat,NaN,NaN,...,NaN,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,96TH AVE NE AND NE 28TH ST\n,NaN
1,K17-103558,A541114,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Neko,Cat,NaN,Male,...,NaN,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,WALLINGFORD AVE N NEAR 150TH ST\n,NaN
2,K17-104020,A543155,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Trixie,Dog,NaN,Female,...,NaN,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,THOMAS RD\n,NaN
3,K17-103994,A543033,Regional Animal Services of King County,FOUND,http://petharbor.com/PublicDetail.asp?searchty...,In Public Home,NaN,Dog,NaN,Female,...,APT,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,10000 MEYDENBAUER WAY SE\nAPT\n,NaN
4,K17-104418,A544774,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Kitty,Cat,NaN,Female,...,NaN,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,76TH AVE SE\n,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404,K17-103413,A540407,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Monster,Cat,NaN,Male,...,KENT,WA,98092.0,KENT,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,"12100 SE 292ND ST\nKENT, WA 98092\n",NaN
405,K17-104617,A545630,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Tyson,Dog,NaN,Male,...,BONNEY LAKE,WA,98391.0,PIERCE COUNTY,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,"21600 121ST STREET CT E\nBONNEY LAKE, WA 98391\n",NaN
406,K17-104272,A544172,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Sadie,Dog,NaN,Female,...,NaN,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,16745 AIR CARGO ROAD\n,NaN
407,K17-103886,A542550,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Maddie,Dog,NaN,Female,...,SEATAC,WA,98188.0,SEATAC,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,"16800 35TH AVE S\nSEATAC, WA 98188\n",NaN
408,K17-103445,A540621,Regional Animal Services of King County,LOST,http://petharbor.com/PublicDetail.asp?searchty...,LOST,Chloe,Cat,NaN,Female,...,NaN,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,146TH N.E. AND 26TH AVE.\n,NaN

In [118]:
pets['Animal_Name'].sort_values()     #Sort by Animal_Name

impound_no
K17-104130          Ace
K17-103964          Ace
K17-103769        Amber
K17-104310        Amore
K17-102943    Anastasia
                ...
K17-103442          NaN
K17-104377          NaN
K17-103782          NaN
K17-103691          NaN
K17-104294          NaN
Name: Animal_Name, Length: 409, dtype: object

In [152]:
pets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 409 entries, 0 to 408
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   impound_no            409 non-null    object
 1   Animal_ID             409 non-null    object
 2   Data_Source           409 non-null    object
 3   Record_Type           409 non-null    object
 4   Link                  409 non-null    object
 5   Current_Location      398 non-null    object
 6   Animal_Name           299 non-null    object
 7   animal_type           409 non-null    object
 8   Age                   228 non-null    object
 9   Animal_Gender         399 non-null    object
 10  Animal_Breed          409 non-null    object
 11  Animal_Color          409 non-null    object
 12  Date                  409 non-null    object
 13  Date_Type             409 non-null    object
 14  Obfuscated_Address    363 non-null    object
 15  City                  314 non-null    object
 16  State                 308 non-null    object
 17  Zip                   311 non-null    float64
 18  jurisdiction          379 non-null    object
 19  obfuscated_latitude   48 non-null     float64
 20  obfuscated_longitude  48 non-null     float64
 21  Image                 398 non-null    object
 22  image_alt_text        409 non-null    object
 23  location_for_map      374 non-null    object
 24  Memo                  228 non-null    object
dtypes: float64(3), object(22)
memory usage: 80.0+ KB

In [153]:
pets['obfuscated_longitude'].sort_values(ascending=True)

166   -122.330362
310   -122.320229
397   -122.315155
195   -122.293832
184   -122.290320
          ...
404           NaN
405           NaN
406           NaN
407           NaN
408           NaN
Name: obfuscated_longitude, Length: 409, dtype: float64

In [159]:
pets[['impound_no','Animal_ID','Animal_Name','animal_type','location_for_map']]\  #\ enter row in python
.sort_values(by=['animal_type','Animal_Name'],ascending=[True,False],inplace=True)

SyntaxError: unexpected character after line continuation character (4109931980.py, line 1)

# Filtering Values

In [169]:
found_pets = pets['Record_Type']=='FOUND'   #Return the table with filter of found_pets==FOUND

In [168]:
pets[found_pets]

NameError: name 'found_pets' is not defined

In [171]:
pets[pets['Record_Type']=='FOUND']  #The same like the code above

,impound_no,Animal_ID,Data_Source,Record_Type,Link,Current_Location,Animal_Name,animal_type,Age,Animal_Gender,...,City,State,Zip,jurisdiction,obfuscated_latitude,obfuscated_longitude,Image,image_alt_text,location_for_map,Memo
0,K17-103806,A542208,Regional Animal Services of King County,FOUND,http://petharbor.com/PublicDetail.asp?searchty...,In Public Home,NaN,Cat,NaN,NaN,...,NaN,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,96TH AVE NE AND NE 28TH ST\n,NaN
3,K17-103994,A543033,Regional Animal Services of King County,FOUND,http://petharbor.com/PublicDetail.asp?searchty...,In Public Home,NaN,Dog,NaN,Female,...,APT,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,10000 MEYDENBAUER WAY SE\nAPT\n,NaN
12,K17-103457,A540735,Regional Animal Services of King County,FOUND,http://petharbor.com/PublicDetail.asp?searchty...,In Public Home,NaN,Dog,NaN,Female,...,NaN,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,216TH ST AND WITTE ROAD\n,NaN
20,K17-103887,A542553,Regional Animal Services of King County,FOUND,http://petharbor.com/PublicDetail.asp?searchty...,In Public Home,NaN,Dog,NaN,Female,...,NaN,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,NaN,NaN
29,K17-103377,A540353,Regional Animal Services of King County,FOUND,http://petharbor.com/PublicDetail.asp?searchty...,In Public Home,NaN,Dog,NaN,Female,...,SAMMAMISH,WA,98075.0,SAMMAMISH,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,"2200 239TH PL SE\nSAMMAMISH, WA 98075\n",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,K17-103442,A540618,Regional Animal Services of King County,FOUND,http://petharbor.com/PublicDetail.asp?searchty...,In Public Home,NaN,Dog,NaN,Female,...,MAPLE VALLEY,WA,98038.0,MAPLE VALLEY,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,"25400 213TH PL SE\nMAPLE VALLEY, WA 98038\n",NaN
380,K17-104377,A544470,Regional Animal Services of King County,FOUND,http://petharbor.com/PublicDetail.asp?searchty...,In Public Home,NaN,Cat,NaN,Female,...,SEATAC,WA,98198.0,SEATAC,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,"21100 INTERNATIONAL BLVD\nSEATAC, WA 98198\n",NaN
383,K17-103782,A542084,Regional Animal Services of King County,FOUND,http://petharbor.com/PublicDetail.asp?searchty...,In Public Home,NaN,Cat,NaN,Female,...,MAPLE VALLEY,WA,98038.0,KING COUNTY,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,"26900 SE 200TH ST\nMAPLE VALLEY, WA 98038\n",NaN
385,K17-103691,A541550,Regional Animal Services of King County,FOUND,http://petharbor.com/PublicDetail.asp?searchty...,In Public Home,NaN,Dog,NaN,Female,...,NaN,NaN,NaN,JURISDICTION,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,NaN,NaN
400,K17-104294,A544208,Regional Animal Services of King County,FOUND,http://petharbor.com/PublicDetail.asp?searchty...,In Public Home,NaN,Cat,NaN,NaN,...,COVINGTON,WA,98042.0,COVINGTON,NaN,NaN,http://www.petharbor.com/get_image.asp?RES=Det...,Image Copyright HLP Inc. 2017,"26400 189TH AVE SE\nCOVINGTON, WA 98042\n",NaN

In [194]:
pets[pets['Record_Type']=='FOUND'][['impound_no','Animal_ID','Record_Type']]  #The same like the code above with definition of what column to get

     impound_no Animal_ID Record_Type
0    K17-103806   A542208       FOUND
3    K17-103994   A543033       FOUND
12   K17-103457   A540735       FOUND
20   K17-103887   A542553       FOUND
29   K17-103377   A540353       FOUND
..          ...       ...         ...
375  K17-103442   A540618       FOUND
380  K17-104377   A544470       FOUND
383  K17-103782   A542084       FOUND
385  K17-103691   A541550       FOUND
400  K17-104294   A544208       FOUND

[200 rows x 3 columns]

In [175]:
big_deals=tran['amount']>500  #bigger tahn 500
tran[big_deals]

,transaction_id,date,product_id,status,payment_method,amount,discount,number_of_items,risk_score,delivery_fee,customer_id,platform
2,002ae1a3-2aa0-4c54-8cd5-061e2ea126e4,2019-09-28,d7fhbn2,approved,MasterCard,600,0.041944,3,0.477638,3,02df87d6-d1cd-494d-a823-97119ec9fece,mobile
9,002ebafd-08da-4002-95cd-08e98aa8e61a,2018-09-24,d72d9gd,approved,Visa,524,0.045329,7,0.661973,3,02fdcd8f-e1a9-43d9-b7c2-142c78fc7e90,mobile
10,002fc5fc-5e5f-4fe6-8191-44155586ee64,2018-08-31,VECOP7OEMFZEZJS3NX5FLTXLM4,approved,PayPal,540,0.036355,9,0.387924,20,02ffb826-75ab-4a8f-b350-478167347a4b,web
11,002fe359-4972-4f38-8a5f-559c079f5bac,2019-03-18,mzdqay78,approved,MasterCard,899,0.011437,3,0.207268,9,0300a275-5844-40e1-b33d-e324b9bd23cf,web
15,00331cf5-df7a-4fcb-a798-c224998c3799,2019-12-10,AEFYC5YOLGTB4IEOAPX3YTFX4E,declined,MasterCard,629,0.022795,3,0.260859,19,0308487d-da1d-473c-a84b-6c42b4617833,web
18,007369ec-e2be-46e8-90d2-3ce0df47eed0,2018-03-19,jm9dzm6,approved,PayPal,730,0.021974,7,0.491678,18,030a901c-ad61-4967-b171-e9fbb70bda65,web
21,012db262-e4b9-495c-b1c7-eca37b583e57,2019-07-12,AARBJEOLFMKYL4SA2WJ2DS2VS4,approved,Visa,815,0.035385,7,0.976911,9,0312ac73-7171-4c25-b35d-5e36ffb4e2e3,web
23,02562fb1-8c0c-47c6-a1b2-ad4d301edbfa,2018-01-11,U5DC7KQPEZTFCYNITQMGRFKFQU,approved,PayPal,556,0.014327,7,0.138404,6,0318a77f-2ba8-474d-9437-08e6bc70ea3b,mobile
25,02cf65ec-1ef0-40a6-b44f-36e4c8b644b4,2019-05-12,dsbjrdd,approved,PayPal,901,0.001208,7,0.684377,10,031e2e7f-2903-40f1-8fe4-d7b6f8663c23,mobile
30,02f21e60-18c1-4e86-9c60-8b8cda7dcc5a,2019-06-21,5g9bkrp,approved,Visa,935,0.023521,8,0.970001,0,032aa453-ed36-4327-a898-a3fec4321594,web
32,02f7d55a-957a-43dd-90bf-78f7220a2d86,2018-10-30,Z4CPPBMASTC47QB52GQ7E7Y3LA,declined,Visa,956,0.021434,5,0.537541,16,04b75a10-7993-47c4-bfc6-a3d100954355,web
35,02ffb826-75ab-4a8f-b350-478167347a4b,2019-12-20,3dzwkdy,approved,PayPal,608,0.001023,8,0.762878,12,0599c49b-2da8-422c-81bf-0617a1d970d2,mobile
36,0300a275-5844-40e1-b33d-e324b9bd23cf,2018-12-19,MU42GW6T7W2Y7EAXL3VLPUPVSU,approved,PayPal,562,0.015332,4,0.478651,0,05a1bacf-2980-415b-a355-e67bca53fcfa,web
37,0300e554-af2b-4e92-8e22-cdbf1daed028,2019-11-25,g4x3rr4,declined,PayPal,694,0.034425,6,0.655149,10,05a83064-6798-4409-b0df-de90d659b89d,mobile
38,03010d47-62c6-43b9-852b-d753097c8813,2019-08-16,6GP3WLFJK2IRJFGYLRA2FXEBTY,approved,MasterCard,563,0.043451,3,0.019966,17,05abb296-c7fd-4c2f-8d47-8a173106d90f,web
39,0307b5fd-7238-4ba6-8402-d41aba331ddf,2019-01-18,ckray5xd,approved,MasterCard,604,0.044472,7,0.968397,0,05b8916d-b217-4caf-afe1-48e64015c1e5,web

In [179]:
not_mc=tran['payment_method']!='MasterCard'
tran[not_mc]

,transaction_id,date,product_id,status,payment_method,amount,discount,number_of_items,risk_score,delivery_fee,customer_id,platform
0,0029e1f5-b648-4787-b13f-563af8dbe7ff,2019-04-16,b3xjvqj,approved,PayPal,152,0.017005,6,0.158209,14,02cf65ec-1ef0-40a6-b44f-36e4c8b644b4,web
1,002a2614-807c-47e4-b1c4-a1198a38e058,2018-01-27,3tkc284,declined,Visa,43,0.017763,1,0.730813,10,02dd9254-23b6-4b32-b53a-17fdfdd8538e,web
3,002c1879-5910-46e8-b26b-ae1ae101d035,2018-09-12,YZCTBC4JWQNE627OCIAQRPABAM,approved,Visa,325,0.009637,7,0.694233,2,02e09992-334b-468f-8be8-924831e7164c,web
4,002c40de-f032-4e10-b5bd-5ee54918cccc,2019-04-14,jj6dcfdg,approved,PayPal,17,0.019172,6,0.039760,1,02eb0fde-b132-447e-9493-6a0d66aacc55,web
5,002d0a5c-0c06-4ba7-9e7e-750157854e9b,2019-02-06,hteg9fnr,approved,PayPal,462,0.023256,6,0.783141,15,02f21e60-18c1-4e86-9c60-8b8cda7dcc5a,web
6,002d71fd-f0e9-4c04-8e25-2eab403231b6,2019-02-12,b76yq78,approved,PayPal,314,0.041843,5,0.170874,20,02f596d4-94cf-4d16-a039-f9a1cc715b8d,mobile
7,002d75df-f207-4218-be5f-e97359c6d7c1,2018-06-17,WJ7DHOEK4WMLFW7OXIJRGYABRY,approved,PayPal,387,0.003122,10,0.014152,15,02f7d55a-957a-43dd-90bf-78f7220a2d86,mobile
8,002da95c-f9e2-4612-a53b-ee12b68a97bf,2019-05-27,7BNHPLRSJPBWTGTLMDJWA6HQXA,declined,CreditCard,176,0.036734,10,0.285476,16,02fda739-e734-40d6-842c-d3cbe588eb23,mobile
9,002ebafd-08da-4002-95cd-08e98aa8e61a,2018-09-24,d72d9gd,approved,Visa,524,0.045329,7,0.661973,3,02fdcd8f-e1a9-43d9-b7c2-142c78fc7e90,mobile
10,002fc5fc-5e5f-4fe6-8191-44155586ee64,2018-08-31,VECOP7OEMFZEZJS3NX5FLTXLM4,approved,PayPal,540,0.036355,9,0.387924,20,02ffb826-75ab-4a8f-b350-478167347a4b,web
12,0030cddd-ec32-4ed2-949a-9d0c72150f9f,2019-05-14,6VOA6SDH5LR27HCFRGU4P7T3DQ,approved,Visa,292,0.024132,3,0.215655,13,0300e554-af2b-4e92-8e22-cdbf1daed028,mobile
14,003208a2-880b-48ec-927e-f4ca23149543,2018-11-17,NX4FRCEJB6HBCVQ6LYQLPQ5KWQ,declined,Visa,87,0.030719,2,0.965585,8,0307b5fd-7238-4ba6-8402-d41aba331ddf,web
16,00340d42-b059-4375-b7ed-f5f7aeb117f1,2019-08-10,W2JHII6424FHXZYIIESZ2GGXBY,approved,PayPal,241,0.036502,2,0.748505,2,03097223-911d-4ce4-a0ea-99b386059eea,web
17,00356bd2-8c35-41e9-b442-8403e2dc1e22,2018-07-29,8qz31w6b,approved,PayPal,196,0.020872,1,0.681486,9,030a7679-8bbd-4a9c-a3a1-87a5bd8c1026,web
18,007369ec-e2be-46e8-90d2-3ce0df47eed0,2018-03-19,jm9dzm6,approved,PayPal,730,0.021974,7,0.491678,18,030a901c-ad61-4967-b171-e9fbb70bda65,web
20,0115d59c-c025-4ff4-a0ee-fd2704becff4,2018-04-23,9gz7qasn,approved,PayPal,119,0.015983,1,0.342077,6,030fea3e-5eff-4714-af98-28e42bf8e86d,web
21,012db262-e4b9-495c-b1c7-eca37b583e57,2019-07-12,AARBJEOLFMKYL4SA2WJ2DS2VS4,approved,Visa,815,0.035385,7,0.976911,9,0312ac73-7171-4c25-b35d-5e36ffb4e2e3,web
22,0225b9ce-027a-4234-a0e5-7792b9c9239a,2019-03-21,8z6ph32,declined,PayPal,228,0.021465,9,0.018606,17,0316fa94-34d1-427e-bd12-21efc963c9bf,web
23,02562fb1-8c0c-47c6-a1b2-ad4d301edbfa,2018-01-11,U5DC7KQPEZTFCYNITQMGRFKFQU,approved,PayPal,556,0.014327,7,0.138404,6,0318a77f-2ba8-474d-9437-08e6bc70ea3b,mobile
24,02c7cf12-9985-4b87-8022-3f210f309050,2018-02-05,MMFZIWL7DZBUCYCYVKRLL6JIA4,approved,PayPal,337,0.000596,9,0.223122,10,03199c18-e4ca-4da2-9f3b-3885e07ff715,web
25,02cf65ec-1ef0-40a6-b44f-36e4c8b644b4,2019-05-12,dsbjrdd,approved,PayPal,901,0.001208,7,0.684377,10,031e2e7f-2903-40f1-8fe4-d7b6f8663c23,mobile
26,02dd9254-23b6-4b32-b53a-17fdfdd8538e,2018-11-17,7r95cmd,approved,PayPal,440,0.042226,10,0.167092,4,0321c9ee-5dbe-4839-90f0-bc89db4fa50c,mobile
28,02e09992-334b-468f-8be8-924831e7164c,2019-12-24,67d9xsj,approved,PayPal,382,0.044017,1,0.284405,14,03248b92-5fa4-44a7-a1c7-4a615ce67f1a,web
29,02eb0fde-b132-447e-9493-6a0d66aacc55,2018-04-20,hh8spmr,approved,Visa,58,0.049504,7,0.233596,17,032a3f09-f574-4394-94c6-15f946f56d91,web
30,02f21e60-18c1-4e86-9c60-8b8cda7dcc5a,2019-06-21,5g9bkrp,approved,Visa,935,0.023521,8,0.970001,0,032aa453-ed36-4327-a898-a3fec4321594,web
32,02f7d55a-957a-43dd-90bf-78f7220a2d86,2018-10-30,Z4CPPBMASTC47QB52GQ7E7Y3LA,declined,Visa,956,0.021434,5,0.537541,16,04b75a10-7993-47c4-bfc6-a3d100954355,web
33,02fda739-e734-40d6-842c-d3cbe588eb23,2019-07-06,7p9nj8j,declined,Visa,368,0.015789,5,0.496224,5,04c314a5-fcb3-4550-8844-6fe118ed2ae9,mobile
34,02fdcd8f-e1a9-43d9-b7c2-142c78fc7e90,2019-02-02,NaN,approved,Visa,413,0.003353,5,0.722797,15,0502f9e6-4609-4e84-8378-c649203e5622,web
35,02ffb826-75ab-4a8f-b350-478167347a4b,2019-12-20,3dzwkdy,approved,PayPal,608,0.001023,8,0.762878,12,0599c49b-2da8-422c-81bf-0617a1d970d2,mobile
36,0300a275-5844-40e1-b33d-e324b9bd23cf,2018-12-19,MU42GW6T7W2Y7EAXL3VLPUPVSU,approved,PayPal,562,0.015332,4,0.478651,0,05a1bacf-2980-415b-a355-e67bca53fcfa,web
37,0300e554-af2b-4e92-8e22-cdbf1daed028,2019-11-25,g4x3rr4,declined,PayPal,694,0.034425,6,0.655149,10,05a83064-6798-4409-b0df-de90d659b89d,mobile

# Filtering Values unique

In [181]:
tran['payment_method'].unique()       #like distinct

array(['PayPal', 'Visa', 'MasterCard', 'CreditCard'], dtype=object)

In [185]:
tran[['payment_method','status','platform']].drop_duplicates(['payment_method','status'])
#all the distinct conjunctions for +2 columns (drop_duplicates) and get the values for the colums(paymeny_method,ststus,platform)

   payment_method    status platform
0          PayPal  approved      web
1            Visa  declined      web
2      MasterCard  approved   mobile
3            Visa  approved      web
6          PayPal  approved   mobile
8      CreditCard  declined   mobile
9            Visa  approved   mobile
11     MasterCard  approved      web
13     MasterCard  declined      web
22         PayPal  declined      web
33           Visa  declined   mobile
37         PayPal  declined   mobile
40     MasterCard  declined   mobile

In [193]:
tran['payment_method'].duplicated(keep='last') #keep the last time you see the distinct value

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8     False
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34    False
35     True
36     True
37    False
38     True
39     True
40    False
Name: payment_method, dtype: bool

In [12]:
tran[tran['date']< '2019']

,transaction_id,date,product_id,status,payment_method,amount,discount,number_of_items,risk_score,delivery_fee,customer_id,platform
1,002a2614-807c-47e4-b1c4-a1198a38e058,2018-01-27,3tkc284,declined,Visa,43,0.017763,1,0.730813,10,02dd9254-23b6-4b32-b53a-17fdfdd8538e,web
3,002c1879-5910-46e8-b26b-ae1ae101d035,2018-09-12,YZCTBC4JWQNE627OCIAQRPABAM,approved,Visa,325,0.009637,7,0.694233,2,02e09992-334b-468f-8be8-924831e7164c,web
7,002d75df-f207-4218-be5f-e97359c6d7c1,2018-06-17,WJ7DHOEK4WMLFW7OXIJRGYABRY,approved,PayPal,387,0.003122,10,0.014152,15,02f7d55a-957a-43dd-90bf-78f7220a2d86,mobile
9,002ebafd-08da-4002-95cd-08e98aa8e61a,2018-09-24,d72d9gd,approved,Visa,524,0.045329,7,0.661973,3,02fdcd8f-e1a9-43d9-b7c2-142c78fc7e90,mobile
10,002fc5fc-5e5f-4fe6-8191-44155586ee64,2018-08-31,VECOP7OEMFZEZJS3NX5FLTXLM4,approved,PayPal,540,0.036355,9,0.387924,20,02ffb826-75ab-4a8f-b350-478167347a4b,web
13,0031bc5c-a945-4023-9b4c-b09dd9cbd138,2018-04-08,7k34qfw,declined,MasterCard,110,0.020343,1,0.159586,6,03010d47-62c6-43b9-852b-d753097c8813,web
14,003208a2-880b-48ec-927e-f4ca23149543,2018-11-17,NX4FRCEJB6HBCVQ6LYQLPQ5KWQ,declined,Visa,87,0.030719,2,0.965585,8,0307b5fd-7238-4ba6-8402-d41aba331ddf,web
17,00356bd2-8c35-41e9-b442-8403e2dc1e22,2018-07-29,8qz31w6b,approved,PayPal,196,0.020872,1,0.681486,9,030a7679-8bbd-4a9c-a3a1-87a5bd8c1026,web
18,007369ec-e2be-46e8-90d2-3ce0df47eed0,2018-03-19,jm9dzm6,approved,PayPal,730,0.021974,7,0.491678,18,030a901c-ad61-4967-b171-e9fbb70bda65,web
19,00850db6-2e9f-4268-87aa-34aa1c652b27,2018-07-23,n474brp,approved,MasterCard,341,0.033084,7,0.876091,8,030fa8f0-ee89-49f6-82e4-82d111ef4ab9,web
20,0115d59c-c025-4ff4-a0ee-fd2704becff4,2018-04-23,9gz7qasn,approved,PayPal,119,0.015983,1,0.342077,6,030fea3e-5eff-4714-af98-28e42bf8e86d,web
23,02562fb1-8c0c-47c6-a1b2-ad4d301edbfa,2018-01-11,U5DC7KQPEZTFCYNITQMGRFKFQU,approved,PayPal,556,0.014327,7,0.138404,6,0318a77f-2ba8-474d-9437-08e6bc70ea3b,mobile
24,02c7cf12-9985-4b87-8022-3f210f309050,2018-02-05,MMFZIWL7DZBUCYCYVKRLL6JIA4,approved,PayPal,337,0.000596,9,0.223122,10,03199c18-e4ca-4da2-9f3b-3885e07ff715,web
26,02dd9254-23b6-4b32-b53a-17fdfdd8538e,2018-11-17,7r95cmd,approved,PayPal,440,0.042226,10,0.167092,4,0321c9ee-5dbe-4839-90f0-bc89db4fa50c,mobile
27,02df87d6-d1cd-494d-a823-97119ec9fece,2018-03-25,bgaqgc8f,approved,MasterCard,438,0.008792,8,0.963923,0,03237ea3-dad8-44be-88eb-2410f4b4a88d,mobile
29,02eb0fde-b132-447e-9493-6a0d66aacc55,2018-04-20,hh8spmr,approved,Visa,58,0.049504,7,0.233596,17,032a3f09-f574-4394-94c6-15f946f56d91,web
32,02f7d55a-957a-43dd-90bf-78f7220a2d86,2018-10-30,Z4CPPBMASTC47QB52GQ7E7Y3LA,declined,Visa,956,0.021434,5,0.537541,16,04b75a10-7993-47c4-bfc6-a3d100954355,web
36,0300a275-5844-40e1-b33d-e324b9bd23cf,2018-12-19,MU42GW6T7W2Y7EAXL3VLPUPVSU,approved,PayPal,562,0.015332,4,0.478651,0,05a1bacf-2980-415b-a355-e67bca53fcfa,web
40,02f7d55a-957a-43dd-90bf-78f7220a2d86,2018-08-28,mgb3m44,declined,MasterCard,100,0.047521,6,0.603461,18,05bb8b02-28a8-471a-ae19-2c8eb55dac53,mobile

In [19]:
cards=tran['Visa','MasterCard']
tran[tran['amount'].isin(cards)]

KeyError: ('Visa', 'MasterCard')

In [36]:
big_deals =tran['amount']> 600
appr_deals =tran['status']=='approved'
tran[big_deals & appr_deals]     #AND

,transaction_id,date,product_id,status,payment_method,amount,discount,number_of_items,risk_score,delivery_fee,customer_id,platform
11,002fe359-4972-4f38-8a5f-559c079f5bac,2019-03-18,mzdqay78,approved,MasterCard,899,0.011437,3,0.207268,9,0300a275-5844-40e1-b33d-e324b9bd23cf,web
18,007369ec-e2be-46e8-90d2-3ce0df47eed0,2018-03-19,jm9dzm6,approved,PayPal,730,0.021974,7,0.491678,18,030a901c-ad61-4967-b171-e9fbb70bda65,web
21,012db262-e4b9-495c-b1c7-eca37b583e57,2019-07-12,AARBJEOLFMKYL4SA2WJ2DS2VS4,approved,Visa,815,0.035385,7,0.976911,9,0312ac73-7171-4c25-b35d-5e36ffb4e2e3,web
25,02cf65ec-1ef0-40a6-b44f-36e4c8b644b4,2019-05-12,dsbjrdd,approved,PayPal,901,0.001208,7,0.684377,10,031e2e7f-2903-40f1-8fe4-d7b6f8663c23,mobile
30,02f21e60-18c1-4e86-9c60-8b8cda7dcc5a,2019-06-21,5g9bkrp,approved,Visa,935,0.023521,8,0.970001,0,032aa453-ed36-4327-a898-a3fec4321594,web
35,02ffb826-75ab-4a8f-b350-478167347a4b,2019-12-20,3dzwkdy,approved,PayPal,608,0.001023,8,0.762878,12,0599c49b-2da8-422c-81bf-0617a1d970d2,mobile
39,0307b5fd-7238-4ba6-8402-d41aba331ddf,2019-01-18,ckray5xd,approved,MasterCard,604,0.044472,7,0.968397,0,05b8916d-b217-4caf-afe1-48e64015c1e5,web

In [38]:
big_deals=tran['amount']> 600
appr_deals=tran['status']=='approved'
tran.loc[big_deals | appr_deals]     #OR

,transaction_id,date,product_id,status,payment_method,amount,discount,number_of_items,risk_score,delivery_fee,customer_id,platform
0,0029e1f5-b648-4787-b13f-563af8dbe7ff,2019-04-16,b3xjvqj,approved,PayPal,152,0.017005,6,0.158209,14,02cf65ec-1ef0-40a6-b44f-36e4c8b644b4,web
2,002ae1a3-2aa0-4c54-8cd5-061e2ea126e4,2019-09-28,d7fhbn2,approved,MasterCard,600,0.041944,3,0.477638,3,02df87d6-d1cd-494d-a823-97119ec9fece,mobile
3,002c1879-5910-46e8-b26b-ae1ae101d035,2018-09-12,YZCTBC4JWQNE627OCIAQRPABAM,approved,Visa,325,0.009637,7,0.694233,2,02e09992-334b-468f-8be8-924831e7164c,web
4,002c40de-f032-4e10-b5bd-5ee54918cccc,2019-04-14,jj6dcfdg,approved,PayPal,17,0.019172,6,0.039760,1,02eb0fde-b132-447e-9493-6a0d66aacc55,web
5,002d0a5c-0c06-4ba7-9e7e-750157854e9b,2019-02-06,hteg9fnr,approved,PayPal,462,0.023256,6,0.783141,15,02f21e60-18c1-4e86-9c60-8b8cda7dcc5a,web
6,002d71fd-f0e9-4c04-8e25-2eab403231b6,2019-02-12,b76yq78,approved,PayPal,314,0.041843,5,0.170874,20,02f596d4-94cf-4d16-a039-f9a1cc715b8d,mobile
7,002d75df-f207-4218-be5f-e97359c6d7c1,2018-06-17,WJ7DHOEK4WMLFW7OXIJRGYABRY,approved,PayPal,387,0.003122,10,0.014152,15,02f7d55a-957a-43dd-90bf-78f7220a2d86,mobile
9,002ebafd-08da-4002-95cd-08e98aa8e61a,2018-09-24,d72d9gd,approved,Visa,524,0.045329,7,0.661973,3,02fdcd8f-e1a9-43d9-b7c2-142c78fc7e90,mobile
10,002fc5fc-5e5f-4fe6-8191-44155586ee64,2018-08-31,VECOP7OEMFZEZJS3NX5FLTXLM4,approved,PayPal,540,0.036355,9,0.387924,20,02ffb826-75ab-4a8f-b350-478167347a4b,web
11,002fe359-4972-4f38-8a5f-559c079f5bac,2019-03-18,mzdqay78,approved,MasterCard,899,0.011437,3,0.207268,9,0300a275-5844-40e1-b33d-e324b9bd23cf,web
12,0030cddd-ec32-4ed2-949a-9d0c72150f9f,2019-05-14,6VOA6SDH5LR27HCFRGU4P7T3DQ,approved,Visa,292,0.024132,3,0.215655,13,0300e554-af2b-4e92-8e22-cdbf1daed028,mobile
15,00331cf5-df7a-4fcb-a798-c224998c3799,2019-12-10,AEFYC5YOLGTB4IEOAPX3YTFX4E,declined,MasterCard,629,0.022795,3,0.260859,19,0308487d-da1d-473c-a84b-6c42b4617833,web
16,00340d42-b059-4375-b7ed-f5f7aeb117f1,2019-08-10,W2JHII6424FHXZYIIESZ2GGXBY,approved,PayPal,241,0.036502,2,0.748505,2,03097223-911d-4ce4-a0ea-99b386059eea,web
17,00356bd2-8c35-41e9-b442-8403e2dc1e22,2018-07-29,8qz31w6b,approved,PayPal,196,0.020872,1,0.681486,9,030a7679-8bbd-4a9c-a3a1-87a5bd8c1026,web
18,007369ec-e2be-46e8-90d2-3ce0df47eed0,2018-03-19,jm9dzm6,approved,PayPal,730,0.021974,7,0.491678,18,030a901c-ad61-4967-b171-e9fbb70bda65,web
19,00850db6-2e9f-4268-87aa-34aa1c652b27,2018-07-23,n474brp,approved,MasterCard,341,0.033084,7,0.876091,8,030fa8f0-ee89-49f6-82e4-82d111ef4ab9,web
20,0115d59c-c025-4ff4-a0ee-fd2704becff4,2018-04-23,9gz7qasn,approved,PayPal,119,0.015983,1,0.342077,6,030fea3e-5eff-4714-af98-28e42bf8e86d,web
21,012db262-e4b9-495c-b1c7-eca37b583e57,2019-07-12,AARBJEOLFMKYL4SA2WJ2DS2VS4,approved,Visa,815,0.035385,7,0.976911,9,0312ac73-7171-4c25-b35d-5e36ffb4e2e3,web
23,02562fb1-8c0c-47c6-a1b2-ad4d301edbfa,2018-01-11,U5DC7KQPEZTFCYNITQMGRFKFQU,approved,PayPal,556,0.014327,7,0.138404,6,0318a77f-2ba8-474d-9437-08e6bc70ea3b,mobile
24,02c7cf12-9985-4b87-8022-3f210f309050,2018-02-05,MMFZIWL7DZBUCYCYVKRLL6JIA4,approved,PayPal,337,0.000596,9,0.223122,10,03199c18-e4ca-4da2-9f3b-3885e07ff715,web
25,02cf65ec-1ef0-40a6-b44f-36e4c8b644b4,2019-05-12,dsbjrdd,approved,PayPal,901,0.001208,7,0.684377,10,031e2e7f-2903-40f1-8fe4-d7b6f8663c23,mobile
26,02dd9254-23b6-4b32-b53a-17fdfdd8538e,2018-11-17,7r95cmd,approved,PayPal,440,0.042226,10,0.167092,4,0321c9ee-5dbe-4839-90f0-bc89db4fa50c,mobile
27,02df87d6-d1cd-494d-a823-97119ec9fece,2018-03-25,bgaqgc8f,approved,MasterCard,438,0.008792,8,0.963923,0,03237ea3-dad8-44be-88eb-2410f4b4a88d,mobile
28,02e09992-334b-468f-8be8-924831e7164c,2019-12-24,67d9xsj,approved,PayPal,382,0.044017,1,0.284405,14,03248b92-5fa4-44a7-a1c7-4a615ce67f1a,web
29,02eb0fde-b132-447e-9493-6a0d66aacc55,2018-04-20,hh8spmr,approved,Visa,58,0.049504,7,0.233596,17,032a3f09-f574-4394-94c6-15f946f56d91,web
30,02f21e60-18c1-4e86-9c60-8b8cda7dcc5a,2019-06-21,5g9bkrp,approved,Visa,935,0.023521,8,0.970001,0,032aa453-ed36-4327-a898-a3fec4321594,web
31,02f596d4-94cf-4d16-a039-f9a1cc715b8d,2019-05-24,A524A3YCILCLJ3HA2TYJTY7AGI,approved,MasterCard,183,0.016493,4,0.243876,16,03bb8e3d-5aed-4e1c-97be-50d02aa27dde,web
32,02f7d55a-957a-43dd-90bf-78f7220a2d86,2018-10-30,Z4CPPBMASTC47QB52GQ7E7Y3LA,declined,Visa,956,0.021434,5,0.537541,16,04b75a10-7993-47c4-bfc6-a3d100954355,web
34,02fdcd8f-e1a9-43d9-b7c2-142c78fc7e90,2019-02-02,NaN,approved,Visa,413,0.003353,5,0.722797,15,0502f9e6-4609-4e84-8378-c649203e5622,web
35,02ffb826-75ab-4a8f-b350-478167347a4b,2019-12-20,3dzwkdy,approved,PayPal,608,0.001023,8,0.762878,12,0599c49b-2da8-422c-81bf-0617a1d970d2,mobile
36,0300a275-5844-40e1-b33d-e324b9bd23cf,2018-12-19,MU42GW6T7W2Y7EAXL3VLPUPVSU,approved,PayPal,562,0.015332,4,0.478651,0,05a1bacf-2980-415b-a355-e67bca53fcfa,web
37,0300e554-af2b-4e92-8e22-cdbf1daed028,2019-11-25,g4x3rr4,declined,PayPal,694,0.034425,6,0.655149,10,05a83064-6798-4409-b0df-de90d659b89d,mobile
38,03010d47-62c6-43b9-852b-d753097c8813,2019-08-16,6GP3WLFJK2IRJFGYLRA2FXEBTY,approved,MasterCard,563,0.043451,3,0.019966,17,05abb296-c7fd-4c2f-8d47-8a173106d90f,web
39,0307b5fd-7238-4ba6-8402-d41aba331ddf,2019-01-18,ckray5xd,approved,MasterCard,604,0.044472,7,0.968397,0,05b8916d-b217-4caf-afe1-48e64015c1e5,web

In [39]:
tran[((tran['amount']>600) & (tran['status']=='approved'))]  # amount and status conditions as well

,transaction_id,date,product_id,status,payment_method,amount,discount,number_of_items,risk_score,delivery_fee,customer_id,platform
11,002fe359-4972-4f38-8a5f-559c079f5bac,2019-03-18,mzdqay78,approved,MasterCard,899,0.011437,3,0.207268,9,0300a275-5844-40e1-b33d-e324b9bd23cf,web
18,007369ec-e2be-46e8-90d2-3ce0df47eed0,2018-03-19,jm9dzm6,approved,PayPal,730,0.021974,7,0.491678,18,030a901c-ad61-4967-b171-e9fbb70bda65,web
21,012db262-e4b9-495c-b1c7-eca37b583e57,2019-07-12,AARBJEOLFMKYL4SA2WJ2DS2VS4,approved,Visa,815,0.035385,7,0.976911,9,0312ac73-7171-4c25-b35d-5e36ffb4e2e3,web
25,02cf65ec-1ef0-40a6-b44f-36e4c8b644b4,2019-05-12,dsbjrdd,approved,PayPal,901,0.001208,7,0.684377,10,031e2e7f-2903-40f1-8fe4-d7b6f8663c23,mobile
30,02f21e60-18c1-4e86-9c60-8b8cda7dcc5a,2019-06-21,5g9bkrp,approved,Visa,935,0.023521,8,0.970001,0,032aa453-ed36-4327-a898-a3fec4321594,web
35,02ffb826-75ab-4a8f-b350-478167347a4b,2019-12-20,3dzwkdy,approved,PayPal,608,0.001023,8,0.762878,12,0599c49b-2da8-422c-81bf-0617a1d970d2,mobile
39,0307b5fd-7238-4ba6-8402-d41aba331ddf,2019-01-18,ckray5xd,approved,MasterCard,604,0.044472,7,0.968397,0,05b8916d-b217-4caf-afe1-48e64015c1e5,web

In [40]:
tran[~((tran['amount']>600) & (tran['status']=='approved'))]  # ~ = it means opposite to the conditions into

,transaction_id,date,product_id,status,payment_method,amount,discount,number_of_items,risk_score,delivery_fee,customer_id,platform
0,0029e1f5-b648-4787-b13f-563af8dbe7ff,2019-04-16,b3xjvqj,approved,PayPal,152,0.017005,6,0.158209,14,02cf65ec-1ef0-40a6-b44f-36e4c8b644b4,web
1,002a2614-807c-47e4-b1c4-a1198a38e058,2018-01-27,3tkc284,declined,Visa,43,0.017763,1,0.730813,10,02dd9254-23b6-4b32-b53a-17fdfdd8538e,web
2,002ae1a3-2aa0-4c54-8cd5-061e2ea126e4,2019-09-28,d7fhbn2,approved,MasterCard,600,0.041944,3,0.477638,3,02df87d6-d1cd-494d-a823-97119ec9fece,mobile
3,002c1879-5910-46e8-b26b-ae1ae101d035,2018-09-12,YZCTBC4JWQNE627OCIAQRPABAM,approved,Visa,325,0.009637,7,0.694233,2,02e09992-334b-468f-8be8-924831e7164c,web
4,002c40de-f032-4e10-b5bd-5ee54918cccc,2019-04-14,jj6dcfdg,approved,PayPal,17,0.019172,6,0.039760,1,02eb0fde-b132-447e-9493-6a0d66aacc55,web
5,002d0a5c-0c06-4ba7-9e7e-750157854e9b,2019-02-06,hteg9fnr,approved,PayPal,462,0.023256,6,0.783141,15,02f21e60-18c1-4e86-9c60-8b8cda7dcc5a,web
6,002d71fd-f0e9-4c04-8e25-2eab403231b6,2019-02-12,b76yq78,approved,PayPal,314,0.041843,5,0.170874,20,02f596d4-94cf-4d16-a039-f9a1cc715b8d,mobile
7,002d75df-f207-4218-be5f-e97359c6d7c1,2018-06-17,WJ7DHOEK4WMLFW7OXIJRGYABRY,approved,PayPal,387,0.003122,10,0.014152,15,02f7d55a-957a-43dd-90bf-78f7220a2d86,mobile
8,002da95c-f9e2-4612-a53b-ee12b68a97bf,2019-05-27,7BNHPLRSJPBWTGTLMDJWA6HQXA,declined,CreditCard,176,0.036734,10,0.285476,16,02fda739-e734-40d6-842c-d3cbe588eb23,mobile
9,002ebafd-08da-4002-95cd-08e98aa8e61a,2018-09-24,d72d9gd,approved,Visa,524,0.045329,7,0.661973,3,02fdcd8f-e1a9-43d9-b7c2-142c78fc7e90,mobile
10,002fc5fc-5e5f-4fe6-8191-44155586ee64,2018-08-31,VECOP7OEMFZEZJS3NX5FLTXLM4,approved,PayPal,540,0.036355,9,0.387924,20,02ffb826-75ab-4a8f-b350-478167347a4b,web
12,0030cddd-ec32-4ed2-949a-9d0c72150f9f,2019-05-14,6VOA6SDH5LR27HCFRGU4P7T3DQ,approved,Visa,292,0.024132,3,0.215655,13,0300e554-af2b-4e92-8e22-cdbf1daed028,mobile
13,0031bc5c-a945-4023-9b4c-b09dd9cbd138,2018-04-08,7k34qfw,declined,MasterCard,110,0.020343,1,0.159586,6,03010d47-62c6-43b9-852b-d753097c8813,web
14,003208a2-880b-48ec-927e-f4ca23149543,2018-11-17,NX4FRCEJB6HBCVQ6LYQLPQ5KWQ,declined,Visa,87,0.030719,2,0.965585,8,0307b5fd-7238-4ba6-8402-d41aba331ddf,web
15,00331cf5-df7a-4fcb-a798-c224998c3799,2019-12-10,AEFYC5YOLGTB4IEOAPX3YTFX4E,declined,MasterCard,629,0.022795,3,0.260859,19,0308487d-da1d-473c-a84b-6c42b4617833,web
16,00340d42-b059-4375-b7ed-f5f7aeb117f1,2019-08-10,W2JHII6424FHXZYIIESZ2GGXBY,approved,PayPal,241,0.036502,2,0.748505,2,03097223-911d-4ce4-a0ea-99b386059eea,web
17,00356bd2-8c35-41e9-b442-8403e2dc1e22,2018-07-29,8qz31w6b,approved,PayPal,196,0.020872,1,0.681486,9,030a7679-8bbd-4a9c-a3a1-87a5bd8c1026,web
19,00850db6-2e9f-4268-87aa-34aa1c652b27,2018-07-23,n474brp,approved,MasterCard,341,0.033084,7,0.876091,8,030fa8f0-ee89-49f6-82e4-82d111ef4ab9,web
20,0115d59c-c025-4ff4-a0ee-fd2704becff4,2018-04-23,9gz7qasn,approved,PayPal,119,0.015983,1,0.342077,6,030fea3e-5eff-4714-af98-28e42bf8e86d,web
22,0225b9ce-027a-4234-a0e5-7792b9c9239a,2019-03-21,8z6ph32,declined,PayPal,228,0.021465,9,0.018606,17,0316fa94-34d1-427e-bd12-21efc963c9bf,web
23,02562fb1-8c0c-47c6-a1b2-ad4d301edbfa,2018-01-11,U5DC7KQPEZTFCYNITQMGRFKFQU,approved,PayPal,556,0.014327,7,0.138404,6,0318a77f-2ba8-474d-9437-08e6bc70ea3b,mobile
24,02c7cf12-9985-4b87-8022-3f210f309050,2018-02-05,MMFZIWL7DZBUCYCYVKRLL6JIA4,approved,PayPal,337,0.000596,9,0.223122,10,03199c18-e4ca-4da2-9f3b-3885e07ff715,web
26,02dd9254-23b6-4b32-b53a-17fdfdd8538e,2018-11-17,7r95cmd,approved,PayPal,440,0.042226,10,0.167092,4,0321c9ee-5dbe-4839-90f0-bc89db4fa50c,mobile
27,02df87d6-d1cd-494d-a823-97119ec9fece,2018-03-25,bgaqgc8f,approved,MasterCard,438,0.008792,8,0.963923,0,03237ea3-dad8-44be-88eb-2410f4b4a88d,mobile
28,02e09992-334b-468f-8be8-924831e7164c,2019-12-24,67d9xsj,approved,PayPal,382,0.044017,1,0.284405,14,03248b92-5fa4-44a7-a1c7-4a615ce67f1a,web
29,02eb0fde-b132-447e-9493-6a0d66aacc55,2018-04-20,hh8spmr,approved,Visa,58,0.049504,7,0.233596,17,032a3f09-f574-4394-94c6-15f946f56d91,web
31,02f596d4-94cf-4d16-a039-f9a1cc715b8d,2019-05-24,A524A3YCILCLJ3HA2TYJTY7AGI,approved,MasterCard,183,0.016493,4,0.243876,16,03bb8e3d-5aed-4e1c-97be-50d02aa27dde,web
32,02f7d55a-957a-43dd-90bf-78f7220a2d86,2018-10-30,Z4CPPBMASTC47QB52GQ7E7Y3LA,declined,Visa,956,0.021434,5,0.537541,16,04b75a10-7993-47c4-bfc6-a3d100954355,web
33,02fda739-e734-40d6-842c-d3cbe588eb23,2019-07-06,7p9nj8j,declined,Visa,368,0.015789,5,0.496224,5,04c314a5-fcb3-4550-8844-6fe118ed2ae9,mobile
34,02fdcd8f-e1a9-43d9-b7c2-142c78fc7e90,2019-02-02,NaN,approved,Visa,413,0.003353,5,0.722797,15,0502f9e6-4609-4e84-8378-c649203e5622,web
36,0300a275-5844-40e1-b33d-e324b9bd23cf,2018-12-19,MU42GW6T7W2Y7EAXL3VLPUPVSU,approved,PayPal,562,0.015332,4,0.478651,0,05a1bacf-2980-415b-a355-e67bca53fcfa,web
37,0300e554-af2b-4e92-8e22-cdbf1daed028,2019-11-25,g4x3rr4,declined,PayPal,694,0.034425,6,0.655149,10,05a83064-6798-4409-b0df-de90d659b89d,mobile
38,03010d47-62c6-43b9-852b-d753097c8813,2019-08-16,6GP3WLFJK2IRJFGYLRA2FXEBTY,approved,MasterCard,563,0.043451,3,0.019966,17,05abb296-c7fd-4c2f-8d47-8a173106d90f,web
40,02f7d55a-957a-43dd-90bf-78f7220a2d86,2018-08-28,mgb3m44,declined,MasterCard,100,0.047521,6,0.603461,18,05bb8b02-28a8-471a-ae19-2c8eb55dac53,mobile